server:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./config/nginx:/etc/nginx/conf.d
    - ./collected_static:/var/interlegis/sapl/collected_static
    - ./media:/var/interlegis/sapl/media
  volumes_from:
    - web
sapldb:
  image: postgres
  environment:
    POSTGRES_PASSWORD: sapl
    POSTGRES_USER: sapl
    POSTGRES_DB: sapl
    PGDATA : /var/lib/postgresql/data/
  volumes:
    - ./postgres-data/data/:/var/lib/postgresql/data/
  ports:
    - "5532:5432"
web:
  build: .
  volumes:
    - .:/var/interlegis/sapl/
    - ./media:/var/interlegis/sapl/media
    - ./collected_static:/var/interlegis/sapl/collected_static
  links:
    - sapldb
